[package]
name = "order_and_chaos"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
console = "0.15.5"
regex = "1.7.1"
structopt = "0.3.26"
eframe = "0.21.3"